name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: l1nxy/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f82182e239950985523d68f28a517330/revisions
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
